Improve performance with lazy loading, useCallback, useMemo, and mini…
gamer-ai/eletypes-frontend pull request #52
Opened 2024-07-01 20:09 UTC by rendi12345678

- Implemented lazy loading for React components to reduce initial load time
- Applied useCallback and useMemo hooks to prevent unnecessary re-renders
- Minified JavaScript files for smaller bundle sizes and faster loading

2024-07-01 20:10 UTC, rendi12345678 commented
and optimize your svg image sir

2024-07-08 04:00 UTC, MUYANGGUO commented
Thanks Rendi!
looks like 
the sentence mode and the words card mode not working correctly.
Type box does not auto focus to the input.

2024-07-08 04:16 UTC, MUYANGGUO requested changes
just couple of places using useCallback but we need to add the set state into it's dependency chain, otherwise I think they probably won't work. 
observed issues:
we losing the auto focus (input), when components are lazy loading with useMemo, can we make the auto focus explicity for each input of the component we touched? another things are due to the useCallBack, I think the error/correct/ css changes are not triggered because of the dependency chain are empty. can test here https://deploy-preview-52--eletypes.netlify.app/

2024-07-08 04:16 UTC, MUYANGGUO commented on src/components/features/SentenceBox/SentenceBox.js
> +}, []);
this seems need to add currSentence, currInput as dependency, instead of empty.

2024-07-08 04:16 UTC, MUYANGGUO commented on src/App.js
> +      <Suspense fallback={null}>
can we add a fallback component instead of having null? probably a loading indicator to handle the waiting to load status, if we want to use Suspense.

2024-07-08 04:16 UTC, MUYANGGUO commented on src/components/features/WordsCard/WordsCard.js
> +  });
ditto, if we want to use usecallback, I think effectively we need to add the setstate in its dependency chain to make it work.

2024-07-08 04:19 UTC, MUYANGGUO commented on src/components/features/WordsCard/WordsCard.js
> +  });
I personally converting handleUpdate with useCallback with this change won't improve too much performance, but let me know if you observed fast renderings.

2024-07-08 13:11 UTC, rendi12345678 commented on src/components/features/WordsCard/WordsCard.js
> +  });
Maybe need some reseach again

2024-07-08 15:29 UTC, closed without merging