Add new chart feature to visualize the data, still beta version :)
gamer-ai/eletypes-frontend pull request #57
Opened 2024-07-15 08:08 UTC by rendi12345678

I havent made it looks good

2024-07-15 08:10 UTC, rendi12345678 commented
https://github.com/user-attachments/assets/2f2ca29f-2ba3-4bcf-8a06-8741d9e08277

2024-07-17 04:16 UTC, MUYANGGUO requested changes
Looks good to me, let me know when you address the comments, happy to merge, when the PR ready, please also update the README,md to add this new stats visual feature, nice works, thanks!

2024-07-17 04:16 UTC, MUYANGGUO commented on src/components/features/TypeBox/Stats.js
> +          stroke="#8884d8"
can we make the stroke a bit bolder? also we would need to use the theme color, I think in your latest preview, it already realized.

2024-07-17 04:16 UTC, MUYANGGUO commented on src/components/features/TypeBox/Stats.js
> +        <CartesianGrid strokeDasharray="3 3" />
I personally think the grid is not necessary, if we want to have a very minimalism design.

2024-07-17 04:16 UTC, MUYANGGUO commented on src/components/features/TypeBox/Stats.js
> +        <TooltipChart />
can we add the tooltip to match the theme color?

2024-07-17 04:16 UTC, MUYANGGUO commented on src/style/global.js
> +min-width: max-content;
nit, format this file with prettier, lol.

2024-07-17 07:28 UTC, rendi12345678 commented on src/style/global.js
> +min-width: max-content;
ok still triying to record errors history

2024-07-17 07:29 UTC, rendi12345678 commented on src/style/global.js
> +min-width: max-content;
![screenshot-20240717-072146Z-all](https://github.com/user-attachments/assets/3e04cf4d-0e53-4f13-8c76-32ca25fcba62)

2024-07-17 07:29 UTC, rendi12345678 commented
![screenshot-20240717-023116Z-all](https://github.com/user-attachments/assets/48b82ece-83e0-4dd6-a7ad-17e731c74977)

2024-07-17 07:30 UTC, rendi12345678 commented
Already match the theme

2024-07-17 07:38 UTC, rendivs925 commented
I am still styling this to meet the request

2024-07-17 07:44 UTC, MUYANGGUO commented
Gotcha, Let me take a look at the newest commit later the day!

2024-07-17 10:31 UTC, rendi12345678 commented
https://github.com/user-attachments/assets/dcfcb4bc-baa0-4c86-bf28-5087def69cfb

Done time to review

2024-07-18 11:09 UTC, MUYANGGUO commented on src/style/global.js
> -    border-left: 1px solid transparent;
hmmm why this block was deleted?

2024-07-18 11:14 UTC, rendi12345678 commented on src/style/global.js
> -    border-left: 1px solid transparent;
oh sorry

2024-07-18 11:16 UTC, MUYANGGUO reviewed
hmmm, 
https://deploy-preview-57--eletypes.netlify.app/ 
btw, you can click into the netlify github action to view the latest deployment of your pull request. 
the preview seems showing non styled on typebox.
and the touch typing mode stats is off, better to check other stats as well.

2024-07-18 11:21 UTC, MUYANGGUO commented
![image](https://github.com/user-attachments/assets/f75710b9-1bf9-425b-8703-6cd01b96d086)
also found some styling off for the dictionary card

2024-07-18 11:22 UTC, MUYANGGUO commented
![image](https://github.com/user-attachments/assets/cc202b2a-1e0f-4817-a607-d860791c4de0)
and here
lol,
sorry this might be due to my laziness just used a global style control. lol

2024-07-18 11:27 UTC, rendivs925 commented
I have recovered removed code

2024-07-18 11:31 UTC, rendi12345678 commented
> ![image](https://private-user-images.githubusercontent.com/39578778/349935297-cc202b2a-1e0f-4817-a607-d860791c4de0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMDI0NTQsIm5iZiI6MTcyMTMwMjE1NCwicGF0aCI6Ii8zOTU3ODc3OC8zNDk5MzUyOTctY2MyMDJiMmEtMWUwZi00ODE3LWE2MDctZDg2MDc5MWM0ZGUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDExMjkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyYWE2Y2YyY2RhMjgzODI4MzZhNmQyN2ZkYjBjYjM4YWUwOTgwNDQyZmRmZjhlNjExNmVmNjQ4ODkxMTQ4YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kEqMBbN5SlMH-oYWbSd0vKiYMR_gmd8-7QObH_Y_ohg) and here lol, sorry this might be due to my laziness just used a global style control. lol

lol

2024-07-18 11:36 UTC, MUYANGGUO commented on src/components/features/TypeBox/Stats.js
> +      <p style={statsTitleStyles}>Raw</p>
Let's still name this one KPM,
since it would be confusing to WPM, because KPM is a stats for keystrokes.

2024-07-18 11:36 UTC, MUYANGGUO commented on src/components/features/TypeBox/Stats.js
> +      <p style={statsTitleStyles}>Raw</p>
```suggestion
      <p style={statsTitleStyles}>KPM</p>
```

2024-07-18 11:42 UTC, MUYANGGUO commented on src/components/features/TypeBox/Stats.js
> +  const roundedRawKpm = Math.round((rawKeyStrokes / countDownConstant) * 60.0);
https://github.com/gamer-ai/eletypes-frontend/blob/5ac13b52bc2ebf180d9bbebf1526ed3d324ca832/src/components/features/TypeBox/TypeBox.js#L383

I realized that showing the KPM here is a bit of off the chart especially we show WPM at the same time. 
the y axis will show a bigger gap.
Let's modify this equation similarly to the wpm calculation

In the tooltip, we call this one "raw WPM"

in the KPM below the chart, we still use the non adjusted raw KPM.

2024-07-18 11:44 UTC, MUYANGGUO commented on src/components/features/TypeBox/Stats.js
> +  const roundedRawKpm = Math.round((rawKeyStrokes / countDownConstant) * 60.0);
Math.round((rawKeyStrokes / (countDownConstant - time)) * 60.0)

2024-07-18 11:44 UTC, rendi12345678 commented on src/components/features/TypeBox/Stats.js
> +  const roundedRawKpm = Math.round((rawKeyStrokes / countDownConstant) * 60.0);
should i removed it ?

2024-07-18 11:45 UTC, rendi12345678 commented on src/components/features/TypeBox/Stats.js
> +  const roundedRawKpm = Math.round((rawKeyStrokes / countDownConstant) * 60.0);
raw kpm and just showing up wpm and errors ?

2024-07-18 11:48 UTC, MUYANGGUO commented on src/components/features/TypeBox/Stats.js
> +  const roundedRawKpm = Math.round((rawKeyStrokes / countDownConstant) * 60.0);
This will make a better visual:
showing two line charts:
(1) highlighted one: the adjusted WPM
(2) dimmed: the raw WPM
so the left Acc stat display will make more sense together with the same scale comparision

The below KPM will just used the Math.round((rawKeyStrokes / countDownConstant) * 60.0) to record the KPM. (without adjusting "/5" )

2024-07-18 11:52 UTC, rendi12345678 commented on src/components/features/TypeBox/Stats.js
> +  const roundedRawKpm = Math.round((rawKeyStrokes / countDownConstant) * 60.0);
ohh okay

2024-07-18 11:52 UTC, rendi12345678 commented on src/components/features/TypeBox/Stats.js
> +  const roundedRawKpm = Math.round((rawKeyStrokes / countDownConstant) * 60.0);
i will adjust it

2024-07-18 11:55 UTC, rendi12345678 commented
(wpmKeyStrokes / 5 / (countDownConstant - countDown)) * 60.0; 
rawKeyStrokes or wpmKeyStrokes ?

2024-07-18 11:56 UTC, MUYANGGUO commented on src/components/features/TypeBox/Stats.js
> +  const roundedRawKpm = Math.round((rawKeyStrokes / countDownConstant) * 60.0);
```suggestion
  const roundedRawWpm = Math.round((rawKeyStrokes / 5 /  (countDownConstant - time)) * 60.0);
```

2024-07-18 11:57 UTC, MUYANGGUO commented on src/components/features/TypeBox/Stats.js
> +            raw: roundedRawKpm,
```suggestion
            raw: roundedRawWpm,
```

2024-07-18 11:58 UTC, MUYANGGUO commented on src/components/features/TypeBox/Stats.js
> +      console.log(payload[0].payload.error);
let's remove the logs

2024-07-18 12:00 UTC, rendi12345678 commented on src/components/features/TypeBox/Stats.js
> +      console.log(payload[0].payload.error);
ok

2024-07-18 12:01 UTC, MUYANGGUO commented on src/components/features/TypeBox/Stats.js
> +      <h2 style={statsValueStyles}>{language}</h2>
eng / chn based on the language mode string

2024-07-18 12:08 UTC, MUYANGGUO commented on src/components/features/TypeBox/Stats.js
> +  const roundedRawKpm = Math.round((rawKeyStrokes / countDownConstant) * 60.0);
ha just realized that this roundedRawWpm was a constant, would need to convert to a functional constant (say getRoundedRawWpm = (rawKeystrokes, time) , so that you can use the time variable from history, when you updating the history state.

2024-07-18 12:17 UTC, rendi12345678 commented
![screenshot-20240718-121739Z-all](https://github.com/user-attachments/assets/a90ab007-3bdd-480d-9d13-c304bb1e2496)
Infinity ?

2024-07-18 12:18 UTC, rendi12345678 commented
const roundedRawWpm = Math.round(
    (rawKeyStrokes / 5 / (countDownConstant - countDown)) * 60.0
  );

2024-07-18 12:21 UTC, MUYANGGUO commented
> const roundedRawWpm = Math.round( (rawKeyStrokes / 5 / (countDownConstant - countDown)) * 60.0 );

would be rawKeyStrokes

2024-07-18 12:23 UTC, MUYANGGUO commented
> ![screenshot-20240718-121739Z-all](https://private-user-images.githubusercontent.com/143745165/349950527-a90ab007-3bdd-480d-9d13-c304bb1e2496.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMDU1MzEsIm5iZiI6MTcyMTMwNTIzMSwicGF0aCI6Ii8xNDM3NDUxNjUvMzQ5OTUwNTI3LWE5MGFiMDA3LTNiZGQtNDgwZC05ZDEzLWMzMDRiYjFlMjQ5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQxMjIwMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNzRlNzc2YmMwYWFkYWY5OGVjOTJlMDZhNDJmOTllMzY2ZTNmZDU5YzY4OTJmODE2NjE3NDI4MDlkOWY1YjY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UFOgyZZ-olj7bmSq5wFa7p3_dqnL9DobYph8FTgiROs) Infinity ?



> ![screenshot-20240718-121739Z-all](https://private-user-images.githubusercontent.com/143745165/349950527-a90ab007-3bdd-480d-9d13-c304bb1e2496.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMDU1MzEsIm5iZiI6MTcyMTMwNTIzMSwicGF0aCI6Ii8xNDM3NDUxNjUvMzQ5OTUwNTI3LWE5MGFiMDA3LTNiZGQtNDgwZC05ZDEzLWMzMDRiYjFlMjQ5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQxMjIwMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNzRlNzc2YmMwYWFkYWY5OGVjOTJlMDZhNDJmOTllMzY2ZTNmZDU5YzY4OTJmODE2NjE3NDI4MDlkOWY1YjY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UFOgyZZ-olj7bmSq5wFa7p3_dqnL9DobYph8FTgiROs) Infinity ?
the KPM would be not using the time offset. just divide with the countdownconstant

2024-07-18 12:23 UTC, MUYANGGUO commented
let me pull your pull request to double check as well.

2024-07-18 12:34 UTC, MUYANGGUO commented
let me try to fix the rest, for example time 1 is 0 , I think I understand why

2024-07-18 12:35 UTC, rendi12345678 commented
> let me try to fix the rest, for example time 1 is 0 , I think I understand why

yeah 0 / 0 = Infinity in js 💀

2024-07-18 12:40 UTC, rendi12345678 commented
![screenshot-20240718-123916Z-all](https://github.com/user-attachments/assets/cbd9ac58-67ba-4bed-b71f-825a84fc1770)
increase header z index to make it above the stats overlay

2024-07-18 13:23 UTC, rendi12345678 commented
How far has the progress been?

2024-07-18 14:17 UTC, MUYANGGUO approved these changes

2024-07-18 14:17 UTC, merged