Add toggle focus mode
gamer-ai/eletypes-frontend pull request #64
Opened 2024-08-16 11:48 UTC by rendi12345678

https://github.com/user-attachments/assets/3ecbfc4d-caf0-421e-b582-7697f3318cc2

2024-08-22 05:10 UTC, MUYANGGUO commented
Let us make this feature a button at the below next to the "word" , it will be only showing up when users at words mode, it also use the local storage to store the user preference. It will not show in the other mode.

2024-08-22 07:05 UTC, rendi12345678 commented
> Let us make this feature a button at the below next to the "word" , it will be only showing up when users at words mode, it also use the local storage to store the user preference. It will not show in the other mode.

ouhh okey sir, i would make it today

2024-08-23 04:36 UTC, rendi12345678 commented
https://github.com/user-attachments/assets/07fbaa45-63cc-4932-b1b8-4e220d389d24

done

2024-08-23 04:44 UTC, MUYANGGUO commented on src/components/features/TypeBox/TypeBox.js
> +      <SocialLinksModal status={status} />
looks like it shows up in the middle of the screen with a backdrop. can we make this less aggressive if it is going to be blocking the user view suddenly.

2024-08-23 04:44 UTC, MUYANGGUO commented on src/components/features/TypeBox/TypeBox.js
> +      <SocialLinksModal status={status} />
I think to ship the ultra zoom mode first, can temporarily remove this sociallinkmodal for now, we would probably ship this later in a separate pull request.
I think the logic is to 5 minutes users are seeing this modal shows up. And it is blocking users to see the status. 
So in that case, let's not make it to a module, but a regular div shows up everytime the game is finished. 
<Visual>
<Stats>
<Share(an icon group)>
when you click any of the social media button, then a modal pops up, to confirm the share. The V0 content would be simply "I have completed a typing challenge with XXX WPM", V1 would be a formatted svg / html/ image that we could create a certificate. 
So I think there is something we need to plan first before shipping in this pull request.

2024-08-23 04:55 UTC, MUYANGGUO commented on src/components/features/TypeBox/TypeBox.js
> +      <SocialLinksModal status={status} />
```suggestion
```

2024-08-23 04:57 UTC, MUYANGGUO commented on src/components/common/FooterMenu.js
> +                      <ZoomInMapIcon fontSize="medium" />
```suggestion
                      <ZoomInMapIcon fontSize="small" />
```

your call lol, let me know what do you think

2024-08-23 04:58 UTC, MUYANGGUO commented on .firebase/hosting.YnVpbGQ.cache
> +static/js/main.97a30f1f.js.map,1724337354227,48d92cc1410ce25a5de188dfe22b94546b79e18b47e81fa2be1583e7c96f5a62
are these the static build file cache for firebase hosting?

2024-08-23 04:59 UTC, MUYANGGUO commented on src/worker/trackHistoryWorker.js
> +self.onmessage = function (e) {
awesome optimizations

2024-08-23 05:21 UTC, rendi12345678 commented on src/components/features/TypeBox/TypeBox.js
> +      <SocialLinksModal status={status} />
yeah i made it hidden

2024-08-23 05:29 UTC, MUYANGGUO approved these changes

2024-08-23 05:30 UTC, MUYANGGUO reviewed
Approved, feel free to merge, and you can add the feature description in the readme.

2024-08-23 05:40 UTC, MUYANGGUO requested changes
let me block the merging first

2024-08-23 07:08 UTC, MUYANGGUO approved these changes

2024-08-23 07:08 UTC, merged

2024-08-23 07:10 UTC, rendi12345678 commented
great